# Generated by Django 3.2.7 on 2021-10-29 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0003_auto_20211029_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='love_count',
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=32, verbose_name='标签名称')),
                ('bkc', models.CharField(default='#7fd5ea', max_length=32, verbose_name='背景色')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_tag_list', to='blogsite.blog', verbose_name='关联博客')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'blog_Tag',
            },
        ),
    ]
