# Generated by Django 3.2.7 on 2021-10-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0005_blog_bkc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='bkc',
            field=models.CharField(blank=True, default='#adb5bd', max_length=32, null=True, verbose_name='背景颜色'),
        ),
    ]
