# Generated by Django 3.2.7 on 2021-11-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0008_auto_20211106_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='图片'),
        ),
    ]
