# Generated by Django 3.2.7 on 2021-11-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0012_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loverelated',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='具体对象id'),
        ),
    ]
