# Generated by Django 3.2.7 on 2021-11-15 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogsite', '0013_alter_loverelated_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='temporary',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='临时用户名'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment_list', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
    ]
