# Generated by Django 3.2.7 on 2021-11-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0014_auto_20211115_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('mobile', models.CharField(max_length=32, verbose_name='联系方式')),
                ('advice', models.CharField(max_length=4096, verbose_name='建议')),
                ('remarks', models.CharField(blank=True, default=None, max_length=8192, null=True, verbose_name='备注信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '反馈建议',
                'verbose_name_plural': '反馈建议',
            },
        ),
    ]
