# Generated by Django 3.2.7 on 2021-11-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0016_auto_20211119_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类专栏', 'verbose_name_plural': '分类专栏'},
        ),
    ]
