# Generated by Django 3.2.7 on 2021-11-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0017_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_origin',
            field=models.BooleanField(default=True, verbose_name='是否原创'),
        ),
    ]
