# Generated by Django 3.2.7 on 2021-11-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0020_alter_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, default=None, max_length=300, null=True, upload_to='cover/%Y/%m/%d', verbose_name='图片地址'),
        ),
    ]
