# Generated by Django 3.2.7 on 2021-09-28 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(default='coins', max_length=64, verbose_name='商品名')),
                ('img', models.ImageField(max_length=512, upload_to='goods/%Y%m', verbose_name='商品图')),
                ('desc', models.CharField(blank=True, max_length=64, null=True, verbose_name='简述')),
                ('price', models.FloatField(verbose_name='原价')),
                ('discount', models.FloatField(default=10, verbose_name='折扣')),
                ('total_stock', models.PositiveIntegerField(default=0, verbose_name='库存')),
                ('remain_stock', models.PositiveIntegerField(default=0, verbose_name='剩余库存')),
                ('status', models.SmallIntegerField(choices=[(1, '开放购买'), (0, '暂未开放')], default=1, verbose_name='商品状态')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'trade_goods',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sn', models.CharField(max_length=128, unique=True, verbose_name='订单号')),
                ('buy_count', models.IntegerField(default=1, verbose_name='购买商品数量')),
                ('buy_amount', models.IntegerField(verbose_name='购买总金额')),
                ('to_user', models.CharField(max_length=32, verbose_name='客户')),
                ('to_email', models.CharField(max_length=128, verbose_name='客户邮箱')),
                ('remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('status', models.SmallIntegerField(choices=[(11, '待支付'), (12, '已支付'), (13, '已取消')], default=11, verbose_name='订单状态')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_list', to='trade.goods', verbose_name='关联商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_list', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'trade_order',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('amount', models.FloatField(help_text='real pay', verbose_name='支付总金额')),
                ('third_sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='第三方支付流水号')),
                ('pay_type', models.SmallIntegerField(choices=[(1, 'Wechat'), (2, 'Zfb')], default=1, verbose_name='支付方式')),
                ('remark', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注信息')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_item', to='trade.order', verbose_name='关联订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_list', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '支付凭证',
                'verbose_name_plural': '支付凭证',
                'db_table': 'trade_payment',
            },
        ),
    ]
