# Generated by Django 3.2.7 on 2021-09-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='img',
            field=models.ImageField(default='avatar/coins.jpg', max_length=512, upload_to='goods/%Y%m', verbose_name='商品图'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(default='鲨币', max_length=64, verbose_name='商品名'),
        ),
    ]
