# Generated by Django 3.2.7 on 2021-11-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='words',
            field=models.CharField(blank=True, default='他很懒，什么也没留下', max_length=64, null=True, verbose_name='个性签名'),
        ),
    ]
