# Generated by Django 3.2.7 on 2021-09-23 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210923_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default=None, editable=False, max_length=150, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True, unique=True, verbose_name='邮箱地址'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default_avatar.jpg', max_length=256, null=True, upload_to='avatar/%Y%m', verbose_name='头像'),
        ),
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, editable=False, max_length=150, verbose_name='用户名')),
                ('ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP地址')),
                ('source', models.CharField(blank=True, max_length=30, null=True, verbose_name='登录来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_record', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '登录历史',
                'verbose_name_plural': '登录历史',
                'db_table': 'auth_login_record',
            },
        ),
    ]
