# Generated by Django 3.2.7 on 2021-11-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, default='http://localhost:8080/static/default_avatar.jpg', max_length=256, null=True, verbose_name='头像'),
        ),
    ]
