# Generated by Django 3.2.7 on 2021-09-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210923_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginrecord',
            name='source',
            field=models.CharField(blank=True, default='web', max_length=30, null=True, verbose_name='登录来源'),
        ),
    ]
