# Generated by Django 3.2.7 on 2021-09-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='逻辑删除'),
        ),
    ]
