# Generated by Django 3.2.7 on 2021-09-27 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20210927_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCoinsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, editable=False, max_length=150, verbose_name='用户名')),
                ('coins_changed_count', models.FloatField(default=0.0, verbose_name='鲨币变化数量')),
                ('coins_before', models.FloatField(default=0.0, verbose_name='鲨币变化前数量')),
                ('coins_after', models.FloatField(default=0.0, verbose_name='鲨币变化后数量')),
                ('reason', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='备注信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coins_record', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '鲨币交易记录',
                'verbose_name_plural': '鲨币交易记录',
                'db_table': 'auth_user_coins_record',
            },
        ),
        migrations.CreateModel(
            name='UserAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, editable=False, max_length=150, verbose_name='用户名')),
                ('remain_coins', models.FloatField(default=0.0, verbose_name='剩余鲨币')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户资产',
                'verbose_name_plural': '用户资产',
                'db_table': 'auth_user_asset',
            },
        ),
    ]
