# Generated by Django 3.2.7 on 2021-09-28 09:42

from django.db import migrations, models
import utils.id


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_userasset_usercoinsrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoinsrecord',
            name='uid',
            field=models.CharField(default=utils.id.uid_gen, editable=False, max_length=64, unique=True, verbose_name='uid'),
        ),
    ]
