# Generated by Django 3.2.7 on 2021-09-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_usercoinsrecord_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userasset',
            name='remain_coins',
            field=models.IntegerField(default=0, verbose_name='剩余鲨币'),
        ),
        migrations.AlterField(
            model_name='usercoinsrecord',
            name='coins_after',
            field=models.IntegerField(default=0, verbose_name='鲨币变化后数量'),
        ),
        migrations.AlterField(
            model_name='usercoinsrecord',
            name='coins_before',
            field=models.IntegerField(default=0, verbose_name='鲨币变化前数量'),
        ),
        migrations.AlterField(
            model_name='usercoinsrecord',
            name='coins_changed_count',
            field=models.IntegerField(default=0, verbose_name='鲨币变化数量'),
        ),
    ]
