# Generated by Django 3.2.7 on 2021-09-28 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20210928_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userasset',
            old_name='remain_coins',
            new_name='coins',
        ),
    ]
