# Generated by Django 3.2.7 on 2021-09-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_rename_remain_coins_userasset_coins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercoinsrecord',
            old_name='coins_changed_count',
            new_name='coins_changed',
        ),
        migrations.AlterField(
            model_name='userasset',
            name='coins',
            field=models.IntegerField(default=0, verbose_name='账户鲨币'),
        ),
    ]
