# Generated by Django 3.2.7 on 2021-09-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20210928_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoinsrecord',
            name='uid',
        ),
    ]
