# Generated by Django 3.2.7 on 2021-11-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_remove_authuser_login_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/default_avatar.jpg', max_length=256, null=True, upload_to='avatar/%Y%m', verbose_name='头像'),
        ),
    ]
