# Generated by Django 3.2.7 on 2021-11-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userasset',
            name='coins',
            field=models.FloatField(default=0.0, verbose_name='账户鲨币'),
        ),
    ]
